package com.salampakistan.model.getflightsresponse

data class InboundRoute(
    val air_segment_ref_key: String,
    val airline: String,
    val airline_logo: String,
    val arrival: String,
    val availability_display_type: String,
    val availability_source: String,
    val baggage_allowance: BaggageAllowance,
    val cabin_class: String,
    val carrier: String,
    val change_of_plane: String,
    val `class`: String,
    val depart: String,
    val distance: String,
    val e_ticket_ability: String,
    val equipment: String,
    val fare_basis: String,
    val fare_info_ref_key: String,
    val flight: String,
    val flight_detail_ref_key: String,
    val flight_number: String,
    val flight_time: Any,
    val flight_time_readable: String,
    val from: String,
    val group: String,
    val link_availability: String,
    val optional_services_indicator: String,
    val participant_level: String,
    val plane: String,
    val polled_availablility_option: String,
    val to: String,
    val travel_time: Int,
    val travel_time_readable: String
)